# Example Travis config. See the entire example: https://github.com/JonathanPorta/ci-build


language: objective-c
osx_image: xcode9.2
rvm:
- 2.1.2
before_install:
- chmod a+x ./BuildScripts/install.sh
- chmod a+x ./BuildScripts/build.sh
install:
- ./BuildScripts/install.sh
script:
- ./BuildScripts/build.sh